### ISSUE TITLE
[ProtoLogger] Debug occasional bug with ProtoLogger/Replay

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#3154]
### Description of the task

To reproduce:
1. Unzip the zip file
2. Run thunderscope_main: `./tbots.py run thunderscope_main -o --blue_log {path to protolog folder}
3. I get this error: `Error parsing message with type 'TbotsProto.World'

[broken_proto_logger.zip](https://github.com/UBC-Thunderbots/Software/files/14546417/broken_proto_logger.zip)
### Acceptance criteria

- [ ] Investigate why this bug exists
- [ ] Fix the issue on ProtoLogger or Replay to handle these edge cases

**Comment by mkhlb** [comment]
[proto_2024_03_23_230504.zip](https://github.com/UBC-Thunderbots/Software/files/14733831/proto_2024_03_23_230504.zip)

While field testing, replay files for field test fixture also give error

```Traceback (most recent call last):
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/thunderscope_main.py", line 338, in <module>
    config=config.configure_replay_view(
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/thunderscope_config.py", line 473, in configure_replay_view
    widgets=configure_base_fullsystem(
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/thunderscope_config.py", line 152, in configure_base_fullsystem
    widget=setup_gl_widget(
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/widget_setup_functions.py", line 75, in setup_gl_widget
    gl_widget = GLWidget(player=player)
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/gl/gl_widget.py", line 145, in __init__
    self.replay_controls = ReplayControls(player=player)
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/replay/replay_controls.py", line 88, in __init__
    ) = common_widgets.create_slider(
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/common/common_widgets.py", line 244, in create_slider
    return create_slider_abs(slider, text, min_val, max_val, tick_spacing)
  File "/home/mkhl/.cache/bazel/_bazel_mkhl/9221f53c0586ef14a687300ed2b2d2ed/execroot/__main__/bazel-out/k8-fastbuild/bin/software/thunderscope/thunderscope_main.runfiles/__main__/software/thunderscope/common/common_widgets.py", line 212, in create_slider_abs
    slider.setMaximum(max_val)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```
